# Generated by Django 5.2.3 on 2025-06-25 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_location_locations_l_is_acti_9f2958_idx_and_more"),
        ("reviews", "0002_alter_review_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["location"], name="reviews_rev_locatio_c50640_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["title"], name="reviews_rev_title_07a416_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["body"], name="reviews_rev_body_6acd4f_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="reviews_rev_rating_2db6dd_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["created_at"], name="reviews_rev_created_bdcc91_idx"
            ),
        ),
    ]
