# Generated by Django 5.2.3 on 2025-06-25 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_reviews_rev_locatio_c50640_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reviewvote",
            index=models.Index(
                fields=["user", "review_id"], name="reviews_rev_user_id_adb81b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewvote",
            index=models.Index(fields=["vote"], name="reviews_rev_vote_05386c_idx"),
        ),
    ]
